name=RohitCore-Config
version=1.0.0
author=Rohit Maji
maintainer=Rohit Maji <rohitmaji2002@gmail.com>
sentence=Configuration management library for Arduino
paragraph=Provides persistent storage for system settings using EEPROM.
category=Data Storage
url=https://github.com/rohitmaji004/RohitCore-Config
architectures=*
depends=RohitCore-Base
